/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _COMMUNICATE_H_RPCGEN
#define _COMMUNICATE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXSTRING 101

typedef char *str;

struct ArticleContent {
	int index;
	str content;
};
typedef struct ArticleContent ArticleContent;

struct reply_1_argument {
	char *arg1;
	int arg2;
};
typedef struct reply_1_argument reply_1_argument;

#define COMMUNICATE_PROG 0x20000001
#define COMMUNICATE_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define POST 1
extern  int * post_1(char *, CLIENT *);
extern  int * post_1_svc(char *, struct svc_req *);
#define READ 2
extern  char ** read_1(CLIENT *);
extern  char ** read_1_svc(struct svc_req *);
#define CHOOSE 3
extern  ArticleContent * choose_1(int , CLIENT *);
extern  ArticleContent * choose_1_svc(int , struct svc_req *);
#define REPLY 4
extern  int * reply_1(char *, int , CLIENT *);
extern  int * reply_1_svc(char *, int , struct svc_req *);
extern int communicate_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define POST 1
extern  int * post_1();
extern  int * post_1_svc();
#define READ 2
extern  char ** read_1();
extern  char ** read_1_svc();
#define CHOOSE 3
extern  ArticleContent * choose_1();
extern  ArticleContent * choose_1_svc();
#define REPLY 4
extern  int * reply_1();
extern  int * reply_1_svc();
extern int communicate_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_str (XDR *, str*);
extern  bool_t xdr_ArticleContent (XDR *, ArticleContent*);
extern  bool_t xdr_reply_1_argument (XDR *, reply_1_argument*);

#else /* K&R C */
extern bool_t xdr_str ();
extern bool_t xdr_ArticleContent ();
extern bool_t xdr_reply_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_COMMUNICATE_H_RPCGEN */
