/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "communicate.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include "peer_server.h"


#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static int *
_post_1 (char * *argp, struct svc_req *rqstp)
{
	return (post_1_svc(*argp, rqstp));
}

static char **
_read_1 (void  *argp, struct svc_req *rqstp)
{
	return (read_1_svc(rqstp));
}

static ArticleContent *
_choose_1 (int  *argp, struct svc_req *rqstp)
{
	return (choose_1_svc(*argp, rqstp));
}

static int *
_reply_1 (reply_1_argument *argp, struct svc_req *rqstp)
{
	return (reply_1_svc(argp->arg1, argp->arg2, rqstp));
}

static void
communicate_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		char *post_1_arg;
		int choose_1_arg;
		reply_1_argument reply_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case POST:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _post_1;
		break;

	case READ:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) _read_1;
		break;

	case CHOOSE:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_ArticleContent;
		local = (char *(*)(char *, struct svc_req *)) _choose_1;
		break;

	case REPLY:
		_xdr_argument = (xdrproc_t) xdr_reply_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _reply_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int main (int argc, char **argv)
{
	//deal with input
    if (argc < 3) {
        std::cout << "Usage: ./serverside server_ip server_port\n";
        exit(1);
    }

    string server_ip((char *) argv[1], strlen((char *)argv[1]));
    int server_port = stoi(argv[2]);
    cout << "Start server at: " << endl;
    cout << server_ip << " " << server_port << endl;
    PeerServer server(server_ip, server_port);

	register SVCXPRT *transp;

	pmap_unset (COMMUNICATE_PROG, COMMUNICATE_VERSION);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, COMMUNICATE_PROG, COMMUNICATE_VERSION, communicate_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (COMMUNICATE_PROG, COMMUNICATE_VERSION, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, COMMUNICATE_PROG, COMMUNICATE_VERSION, communicate_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (COMMUNICATE_PROG, COMMUNICATE_VERSION, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");


	exit (1);
	/* NOTREACHED */
}
