/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "communicate.h"


void
communicate_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	char *post_1_arg1;
	char * *result_2;
	ArticleContent  *result_3;
	int choose_1_arg1;
	int  *result_4;
	char *reply_1_arg1;
	int reply_1_arg2;

#ifndef	DEBUG
	clnt = clnt_create (host, COMMUNICATE_PROG, COMMUNICATE_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = post_1(post_1_arg1, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = read_1(clnt);
	if (result_2 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = choose_1(choose_1_arg1, clnt);
	if (result_3 == (ArticleContent *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = reply_1(reply_1_arg1, reply_1_arg2, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	communicate_prog_1 (host);
exit (0);
}
